# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(699, 524)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 701, 531))
        self.stackedWidget.setStyleSheet("QWidget{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(240, 111, 115, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(170, 90, 391, 51))
        self.label_2.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"font: 12pt \"Noto Sans\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setGeometry(QtCore.QRect(250, 290, 221, 41))
        self.pushButton.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(171, 213, 218);")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(300, 40, 131, 51))
        self.label.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"font: 18pt \"Noto Sans\";\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.label_11 = QtWidgets.QLabel(self.page_9)
        self.label_11.setGeometry(QtCore.QRect(280, 60, 181, 51))
        self.label_11.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"font: 18pt \"Noto Sans\";\n"
"color: rgb(255, 255, 255);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.page_9)
        self.label_12.setGeometry(QtCore.QRect(170, 170, 141, 41))
        self.label_12.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"font: 12pt \"Noto Sans\";\n"
"color: rgb(255, 255, 255);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.page_9)
        self.lineEdit_4.setGeometry(QtCore.QRect(360, 180, 161, 27))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.page_9)
        self.lineEdit_5.setGeometry(QtCore.QRect(360, 260, 161, 27))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_13 = QtWidgets.QLabel(self.page_9)
        self.label_13.setGeometry(QtCore.QRect(170, 250, 141, 41))
        self.label_13.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"font: 12pt \"Noto Sans\";\n"
"color: rgb(255, 255, 255);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.pushButton_13 = QtWidgets.QPushButton(self.page_9)
        self.pushButton_13.setGeometry(QtCore.QRect(260, 350, 221, 41))
        self.pushButton_13.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(171, 213, 218);\n"
"")
        self.pushButton_13.setObjectName("pushButton_13")
        self.stackedWidget.addWidget(self.page_9)
        self.page_17 = QtWidgets.QWidget()
        self.page_17.setObjectName("page_17")
        self.label_37 = QtWidgets.QLabel(self.page_17)
        self.label_37.setGeometry(QtCore.QRect(160, 20, 361, 51))
        self.label_37.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"font: 18pt \"Noto Sans\";\n"
"color: rgb(255, 255, 255);")
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.pushButton_31 = QtWidgets.QPushButton(self.page_17)
        self.pushButton_31.setGeometry(QtCore.QRect(280, 170, 141, 41))
        self.pushButton_31.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(171, 213, 218);")
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(self.page_17)
        self.pushButton_32.setGeometry(QtCore.QRect(450, 420, 141, 41))
        self.pushButton_32.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(171, 213, 218);")
        self.pushButton_32.setObjectName("pushButton_32")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.page_17)
        self.lineEdit_9.setGeometry(QtCore.QRect(30, 90, 631, 31))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.pushButton_35 = QtWidgets.QPushButton(self.page_17)
        self.pushButton_35.setGeometry(QtCore.QRect(140, 420, 141, 41))
        self.pushButton_35.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(171, 213, 218);")
        self.pushButton_35.setObjectName("pushButton_35")
        self.label_38 = QtWidgets.QLabel(self.page_17)
        self.label_38.setGeometry(QtCore.QRect(170, 290, 361, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"font: 22pt \"Noto Sans\";\n"
"color: rgb(255, 0, 0);")
        self.label_38.setText("")
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.page_17)
        self.label_39.setGeometry(QtCore.QRect(170, 240, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"font: 14pt \"Noto Sans\";\n"
"color: rgb(0, 0, 0);")
        self.label_39.setText("")
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.stackedWidget.addWidget(self.page_17)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Sign in or Create an account"))
        self.pushButton.setText(_translate("Form", "Log in"))
        self.label.setText(_translate("Form", "Welcome"))
        self.label_11.setText(_translate("Form", "Login"))
        self.label_12.setText(_translate("Form", "user"))
        self.label_13.setText(_translate("Form", "Password"))
        self.pushButton_13.setText(_translate("Form", "Log in"))
        self.label_37.setText(_translate("Form", "Fake Face Detection System"))
        self.pushButton_31.setText(_translate("Form", "Browse"))
        self.pushButton_32.setText(_translate("Form", "Submit"))
        self.pushButton_35.setText(_translate("Form", "clear"))
